# Taskfile.yml
version: '3'

tasks:

  build:
    desc: "Build the driver binary"
    cmds:
      - go build -o bin/driver cmd/main.go

  docker-build:
    desc: "Build and load Docker image into kind"
    cmds:
      - ./scripts/build.sh

  e2e:
    desc: "Run e2e tests"
    cmds:
      - ./scripts/e2e.sh

  cleanup:
    desc: "Clean everything"
    cmds:
      - ./scripts/cleanup.sh