apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo
  labels:
    app: csi-driver-hostpath-on-steriod
    csi-driver-example: "true"
spec:
  storageClassName: hostpath-on-steriod
  resources:
    requests:
      storage: 1G
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
