apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-immediate
spec:
  storageClassName: hostpath-on-steriod-immediate
  resources:
    requests:
      storage: 1G
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
