apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-waitforfirstconsumer
spec:
  storageClassName: hostpath-on-steriod-waitforfirstconsumer
  resources:
    requests:
      storage: 1G
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
